name: Build Python Package

on:
  release:
    types: [published]

  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: 'Version number for the package.'
  #       required: true
  #       default: '0.0.8'

# I've had looks at...
# https://github.com/jugmac00/will-it-build/blob/main/action.yml
# https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives
# https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#packaging-your-project

# I'm intentionally not using setup-python here,
# instead relying on the pre-installed python3.
# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

jobs:
  build_python_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - run: ./.github/scripts/inject-version.sh ${{ github.event.inputs.version }}
    - run: python3 -m pip install --upgrade build
    - run: python3 -m build
    - run: ls -AlF dist/
    - name: Proved GITHUB_TOKEN
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >>$GITHUB_ENV
    - name: Upload build artifacts to the release.
      run: |
        if [[ $GITHUB_EVENT_NAME == release ]]; then
          ./.github/scripts/upload-dist-artifacts.sh
        fi
