name: Print Environment

on:
  workflow_dispatch:
  release:
    types: [created, published]

jobs:
  print_environment:
    runs-on: ubuntu-20.04
    steps:

    - name: Print Environment
      run: "printenv | sort"

    - name: Print Event
      run: "cat $GITHUB_EVENT_PATH"
